name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"
      - name: Run Lua syntax check
        run: |
          shopt -s nullglob
          for file in *.lua; do
            echo "::group::Syntax check: $file"
            lua -p "$file"
            echo "::endgroup::"
          done
      # If you have tests, uncomment the following:
      # - name: Install busted
      #   run: luarocks install busted
      # - name: Run tests
      #   run: busted
