name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"
      - name: Run Lua syntax check
        run: |
          for file in *.lua; do
            lua -p "$file"
          done
      # Optionally add test runner here if you have tests (e.g., busted)
